########################################
# QX Ruleset - CF Worker Edition (v4)
# 2026.05.26 / self-hosted
########################################

# === API Redirect to Cloudflare Worker ===
^https?:\/\/youtubei(?:-att)?\.googleapis\.com\/(youtubei\/v1\/(browse|next|player|search|reel\/reel_watch_sequence|guide|account\/get_setting|get_watch|log_event))(\?(.*))?$ url 307 https://stream.maasea.workers.dev/$1?blockUpload=true&blockImmersive=true&blockShorts=false&captionLang=off&lyricLang=off&$3

# === Video Ad Block ===
^https?:\/\/[\w-]+\.googlevideo\.com\/.*&oad url reject-200

# === Tracker Block ===
^https?:\/\/(www|s)\.youtube\.com\/api\/stats\/ads url reject-200
^https?:\/\/(www|s)\.youtube\.com\/(pagead|ptracking) url reject-200
^https?:\/\/s\.youtube\.com\/api\/stats\/qoe\?adcontext url reject-200

# === MITM ===
hostname = *.googlevideo.com, youtubei.googleapis.com, youtubei-att.googleapis.com, www.youtube.com, s.youtube.com
