########################################
# QX Ruleset - Media Helper (v2)
# 2026.05.26 / self-hosted
########################################

# === Usage ===
# 1. [general] must include: udp_drop_list=443
# 2. [mitm] must include the hostname below
# 3. Trust MITM certificate in QX settings


# === Net Filter ===
^(https?:\/\/[\w-]+\.googlevideo\.com\/(?!dclk_video_ads).+?)&ctier=L(&.+?),ctier,(.+) url 302 $1$2$3
^https?:\/\/[\w-]+\.googlevideo\.com\/initplayback.+&oad url reject-200
^https?:\/\/[\w-]+\.googlevideo\.com\/(?!(dclk_video_ads|videoplayback\?|initplayback)).+&oad url reject-200


# === Core Engine ===
^https?:\/\/youtubei(?:-att)?\.googleapis\.com\/youtubei\/v1\/(browse|next|player|search|reel\/reel_watch_sequence|guide|account\/get_setting|get_watch) url script-response-body https://raw.githubusercontent.com/Xo776/by-yt/main/media.js


# === Tracker Block ===
^https?:\/\/(www|s)\.youtube\.com\/api\/stats\/ads url reject-200
^https?:\/\/(www|s)\.youtube\.com\/(pagead|ptracking) url reject-200
^https?:\/\/s\.youtube\.com\/api\/stats\/qoe\?adcontext url reject-200

# === MITM ===
hostname = *.googlevideo.com, youtubei.googleapis.com, youtubei-att.googleapis.com, www.youtube.com, s.youtube.com
